from marshmallow import fields
from schemas import ma

# Define the order 
class OrderSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    customer_id = fields.Integer(required=True)
    product_id = fields.Integer(required=True)
    quantity = fields.Integer(required=True)
    total_price = fields.Float(required=True)

    class Meta:
        fields = ("id", "customer_id", "product_id", "quantity", "total_price")

# Create instances of the schema
order_schema = OrderSchema()
orders_schema = OrderSchema(many=True)