from marshmallow import fields
from schemas import ma

# Define the product 
class ProductSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    name = fields.String(required=True)
    price = fields.Float(required=True)

    class Meta:
        fields = ("id", "name", "price")

# Create instances of the schema
product_schema = ProductSchema()
products_schema = ProductSchema(many=True)