from marshmallow import fields
from schemas import ma

# Define the production 
class ProductionSchema(ma.Schema):
    id = fields.Integer(required=False) # id is autogenerated
    product_id = fields.Integer(required=True)
    quantity_produced = fields.Integer(required=True)
    date_produced = fields.String(required=True) # changed this from Date to String because of issues with unit testing

    class Meta:
        fields = ("id", "product_id", "quantity_produced", "date_produced")

# Create instances of the schema
production_schema = ProductionSchema()
productions_schema = ProductionSchema(many=True)